server:
  port: 8080

spring:
  application:
    name: mybatis
  datasource:
    url: jdbc:mysql://192.168.1.69:3306/test?useUnicode=true&characterEncoding=utf8
    username: sa
    password: some_pass
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  model-package: com.cxy.test.model

eureka:
  instance:
    prefer-ip-address: true
#    ip-address: 10.10.14.240
  client:
    service-url:
      defaultZone: http://localhost:8701/eureka