server:
  port: 8080

logging:
  level:
    tk.mybatis: TRACE

mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.cxy.test.generator.model

mapper:
  mappers: com.cxy.test.generator.config..tkmapper.MyMapper
  not-empty: false
  identity: MYSQL

spring:
  datasource:
    url: jdbc:mysql://192.168.1.69:3306/test?useUnicode=true&characterEncoding=utf8
    username: sa
    password: some_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    #durid补充设置
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小等待连接数量，最大等待连接数量，最大连接数
    initialSize: 5
    minIdle: 1
    maxIdle: 10
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #spring.datasource.useGlobalDataSourceStat=true